language: python
python:
  - '2.7'
  - '3.5'
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-dev.txt
script:
  - py.test --cov pageview_digest --cov-report term-missing
after_success:
  - coveralls
sudo: false